version: "3.9"
services:
  db:
    container_name: ${TYPEORM_CONNECTION}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - ./PostgeSQL/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./PostgeSQL/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      #- ./PostgeSQL/data:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    restart: unless-stopped
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge
