version: "3.8"
services:
  db:
    container_name: ${TYPEORM_CONNECTION}
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      TZ: GMT-4
      PGTZ: GMT-4
    volumes:
      #- ./PostgeSQL/data:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    restart: unless-stopped
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge
