version: "3.9"
services:
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./PostgeSQL/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./PostgeSQL/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      #- ./PostgeSQL/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge
